package com.example.dsa_duel.models

// ── BOT PROFILE ───────────────────────────────────────────────────

/**
 * Represents the AI bot opponent in a duel.
 * Generated by BotGenerator.kt based on player's ELO.
 *
 * This is a plain data class — not a Room entity.
 * Bots are ephemeral — created for one duel, then discarded.
 * They are never stored in the database.
 */
data class BotProfile(

    // Display name shown on VS screen and result screen
    // Examples: "algo_shadow", "byte_ghost", "null_ptr_"
    val name: String,

    // Bot's ELO rating — always within ±100 of player's ELO
    // Shown on VS screen and result screen
    val eloRating: Int,

    // How many seconds into the duel the bot "answers"
    // Counts DOWN from total time.
    // Example: totalTime=120, solveTimeSeconds=80
    //   → bot answers when timer shows 40 seconds left
    // Higher ELO bot → answers faster (lower solveTimeSeconds)
    val solveTimeSeconds: Int,

    // Probability (0.0 to 1.0) that bot answers CORRECTLY
    // Higher ELO bot → higher accuracy
    // Example: 0.85 = 85% chance bot gets it right
    val accuracy: Float,

    // Bot's rank name for display on VS screen
    // Example: "GOLD II", "PLATINUM I"
    val rankName: String,

    // Bot's rank emoji for display
    // Example: "🥇", "⚡", "💎"
    val rankEmoji: String
)

// ── DUEL RESULT (lightweight summary for history) ─────────────────

/**
 * A lightweight record of a completed duel.
 * Stored in Room via DuelHistoryEntity (future feature).
 * Used to populate the "Recent Battles" list on Home screen.
 *
 * Separate from DuelState.Result because:
 *   - DuelState.Result is in-memory, ephemeral
 *   - DuelResult is the saved record for history display
 */